#!/bin/bash
set -e

echo "Installing uv-deps-switcher..."
uv tool install git+https://github.com/PhoPersonalOrg/uv-deps-switcher.git || true

# echo "Deploying templates..."
# uv-deps-switcher --deploy-templates || true

echo "Switching to external dependencies..."
uv-deps-switcher external --checkout-dest "./EXTERNAL" --yes || true

# echo "Fixing dependencies to allow resolution..."
# # Update dependency ranges that cause conflicts in the external checkouts
# sed -i 's/"numba>=0.59.0,<0.57"/"numba>=0.59.0"/g' EXTERNAL/pyPhoCoreHelpers/pyproject.toml || true
# sed -i 's/numba>=0.56.4/numba>=0.59.0/g' EXTERNAL/pyPhoCoreHelpers/pyproject.toml || true
# # In PhoPyMNEHelper we need to fix numpy and pyxdf constraints as earlier versions conflicted with older corehelpers numpy bounds
# sed -i 's/pyxdf>=1.17.2/pyxdf>=1.16.8/g' EXTERNAL/PhoPyMNEHelper/pyproject.toml || true
# sed -i 's/numpy>=2.2.6/numpy>=1.23.2/g' EXTERNAL/PhoPyMNEHelper/pyproject.toml || true
# # Remove bad source block that causes resolution errors in github actions where mne-python is missing
# sed -i '/mne = { path = "..\/..\/mne-python", editable = true }/d' EXTERNAL/PhoPyMNEHelper/pyproject.toml || true

# # Add missing ipywidgets and nptyping requirement to pyproject.toml as they are required by pyPhoCoreHelpers but was missing/commented out
# # NOTE: match the trailing comma too so we don't leave a dangling ",," behind (invalid TOML)
# sed -i 's/#"np2typing>=2.6.3",/"nptyping>=2.5.0",\n    "ipywidgets>=8.1.8",\n    "nbformat",\n    "ipython",/g' pyproject.toml || true

# # ADD THIS LINE: Sanitize any trailing or double commas generated by the templating step
# sed -i 's/,,/,/g' pyproject.toml

# echo "Fixing dependencies to allow resolution..."
# # 1. Your previous fix for the double commas
# sed -i 's/,,/,/g' pyproject.toml

# # 2. ADD THESE LINES: Update numba in the cloned pyPhoCoreHelpers to support Python 3.11+
# echo "Patching pyPhoCoreHelpers numba dependency..."
# if [ -f "./EXTERNAL/pyPhoCoreHelpers/pyproject.toml" ]; then
#     # Replaces strings like "numba==0.56.0" or "numba<0.57" with "numba>=0.57.1"
#     sed -i 's/"numba[^"]*"/"numba>=0.57.1"/g' ./EXTERNAL/pyPhoCoreHelpers/pyproject.toml
#     sed -i "s/'numba[^']*'/'numba>=0.57.1'/g" ./EXTERNAL/pyPhoCoreHelpers/pyproject.toml
# fi

# # (Optional fallback if it uses setup.py instead of pyproject.toml)
# if [ -f "./EXTERNAL/pyPhoCoreHelpers/setup.py" ]; then
#     sed -i 's/"numba[^"]*"/"numba>=0.57.1"/g' ./EXTERNAL/pyPhoCoreHelpers/setup.py
#     sed -i "s/'numba[^']*'/'numba>=0.57.1'/g" ./EXTERNAL/pyPhoCoreHelpers/setup.py
# fi


echo "Pinning Python version..."
uv python pin 3.11.11

# echo "Restricting uv resolution to Linux..."
# # Check if [tool.uv] exists; if so, append the environment restriction. If not, create the block.
# if grep -q "\[tool.uv\]" pyproject.toml; then
#     sed -i '/\[tool.uv\]/a environments = ["sys_platform == \"linux\""]' pyproject.toml
# else
#     echo -e "\n[tool.uv]\nenvironments = [\"sys_platform == 'linux'\"]" >> pyproject.toml
# fi

echo "Setting up virtual environment..."
# uv venv --clear
uv lock
uv sync

echo "Setup complete! You can now run tests with 'xvfb-run uv run pytest tests'"
